# Generated by Django 5.2.17 on 2026-09-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('counterparty', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('method', models.CharField(max_length=50)),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_category', models.CharField(max_length=100)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction')),
            ],
        ),
    ]
